apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  labels:
    app.kubernetes.io/name: volsync
    app.kubernetes.io/managed-by: kustomize
  name: replicationsource-sample
spec:
  # TODO(user): Add fields here
