apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  labels:
    app.kubernetes.io/name: volsync
    app.kubernetes.io/managed-by: kustomize
  name: replicationdestination-sample
spec:
  # TODO(user): Add fields here
